### PR TITLE
Convert relative paths to absolute when checking links

### LINKED ISSUE #28: Can type incorrect path and still work but breaks links

### PR DESCRIPTION
**Pull request by mattcopas**
This solution takes a relative link to check (eg `../../test/a`) and converts it to an absolute link (`/docs/test/a`). 

This also adds a second attempt at finding headers for links - ie if finding headers for `/a` fails, then try again for `/a/` 

Closes #28

### CODE REVIEW

File: theme/plugins/check-links/index.js [hunk 1]
```diff
@@ -6,8 +6,28 @@ function getCacheKey(node) {
...
+
+function convertToBasePath(link, path) {
+  if (link.startsWith('../')) {
+    // Convert the relative link to an absolute one
+    const moveUpDirectoryCount = (link.match(/\.\.\//g) || []).length
+    let pathWithoutTrailingSlash = path[path.length - 1] === '/' ? path.slice(0, path.length - 1) : path
+    const pathSlashCount = (path.match(/\//g) || []).length
+    const indexToSliceTo = getPosition(pathWithoutTrailingSlash, '/', pathSlashCount - moveUpDirectoryCount) + 1
+    const slicedPath = pathWithoutTrailingSlash.slice(0, indexToSliceTo)
+    const slicedLink = link.slice(moveUpDirectoryCount * 3, link.length)
```
Comment (stuarthendren) [inline theme/plugins/check-links/index.js:21]: NIT don't need the end index here

File: theme/plugins/check-links/index.js [hunk 2]
```diff
@@ -6,8 +6,28 @@ function getCacheKey(node) {
   return `check-links-${node.id}-${node.internal.contentDigest}`
 }
 
+function getPosition(string, subString, index) {
+  return string.split(subString, index).join(subString).length;
+}
+
+function convertToBasePath(link, path) {
+  if (link.startsWith('../')) {
+    // Convert the relative link to an absolute one
```
Comment (stuarthendren) [inline theme/plugins/check-links/index.js:15]: NIT prefer named methods over comments

File: theme/plugins/check-links/index.js [hunk 3]
```diff
@@ -6,8 +6,28 @@ function getCacheKey(node) {
   return `check-links-${node.id}-${node.internal.contentDigest}`
 }
 
+function getPosition(string, subString, index) {
```
Comment (stuarthendren) [inline theme/plugins/check-links/index.js:9]: NIT better getNthPosition(string, substring, n) or getPositionOfNthOccurrance

File: example/docs/tests/a/index.md [hunk 4]
```diff
@@ -2,15 +2,15 @@
 
 This file is the index.md in the `a` folder. It appears on the path as with a trailing slash.
 
-To link relatively to the folder `b` you should use, [b/](b/) or [b/index](b/index) the last has the advantage that is also works in the raw markdown. A full link is also valid [/tests/a/b/](/tests/a/b/) or [/tests/a/b/index](/tests/a/b/index) linking to headings is also supported [b/#link-test](b/#link-test) and [b/index#link-test](b/index#link-test).
+To link relatively to the folder `b` you should use, [b/](b/) or [b/index](b/index) the last has the advantage that is also works in the raw markdown. A full link is also valid [/tests/a/b/](/tests/a/b/) or [/tests/a/b/index](/tests/a/b/index) linking to headings is also supported [b/#link-test](b/#link-test) and [b/index#link-test](b/index#link-test). 
+
+You can also link 'up' directories, for example: [../a](../a), [../a/mdTest](../../tests/mdTest), [../../tests/a/b#link-test](../../tests/a/b#link-test)
```
[the remark this answers is not in the document]
Comment (mattcopas) [reply example/docs/tests/a/index.md:7]: Updated link text

Not intending to change the links themselves. Agree they are contrived but they're there to demonstrate the concepts of "upward relative" linking and they do that adequately IMO.
